steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "_NODE_ENV=$_NODE_ENV",
        "-t",
        "asia.gcr.io/$PROJECT_ID/$_SERVICE_NAME:$_TAG_NAME", # service_nameは勝手に決まる
        ".",
      ]

substitutions:
  _NODE_ENV: "production"
  _TAG_NAME: "latest"
  _SERVICE_NAME: "randoom"
images: ["asia.gcr.io/$PROJECT_ID/$_SERVICE_NAME:$_TAG_NAME"]
